// automatically generated by the FlatBuffers compiler, do not modify

package com.nvidia.spark.rapids.format;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BlockMeta extends Table {
  public static BlockMeta getRootAsBlockMeta(ByteBuffer _bb) { return getRootAsBlockMeta(_bb, new BlockMeta()); }
  public static BlockMeta getRootAsBlockMeta(ByteBuffer _bb, BlockMeta obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public BlockMeta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * metadata about a shuffle block
   */
  public TableMeta tableMetas(int j) { return tableMetas(new TableMeta(), j); }
  public TableMeta tableMetas(TableMeta obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tableMetasLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createBlockMeta(FlatBufferBuilder builder,
      int table_metasOffset) {
    builder.startObject(1);
    BlockMeta.addTableMetas(builder, table_metasOffset);
    return BlockMeta.endBlockMeta(builder);
  }

  public static void startBlockMeta(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addTableMetas(FlatBufferBuilder builder, int tableMetasOffset) { builder.addOffset(0, tableMetasOffset, 0); }
  public static int createTableMetasVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTableMetasVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBlockMeta(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

